#
# MariaDB Galera 10.0
#
mariadb-galera-conf:
  image: deisNode0:5500/mariadb-galera-conf
  container_name: mariadb-galera-conf
  command: "/bin/sh"
mariadb-galera-data:
  image: deisNode0:5500/mariadb-galera-data
  container_name: mariadb-galera-data
  command: "/bin/sh"
mariadb-galera:
  restart: always
  image: monami0ya/docker-mariadb-10.0-galera
  net: host
  privileged: true
  volumes_from:
  - mariadb-galera-conf
  - mariadb-galera-data
  container_name: mariadb-galera
  environment:
  - MODE=node
#
# Redis + Sentinel
#
redis-data:
  image: deisNode0:5500/redis-data
  container_name: redis-data
  command: "sleep 100000"
redis:
  restart: always
  net: host
  volumes_from:
  - redis-data
  container_name: redis
  image: "redis:3"
  command: redis-server
sentinel:
  restart: always
  net: host
  volumes_from:
  - redis-data
  container_name: sentinel
  image: "redis:3"
  command: "redis-sentinel /data/sentinel.conf"
#
# MongoDB 2.6.5
#
mongo-data:
  image: deisNode0:5500/mongo-data
  container_name: mongo-data
mongo:
  restart: always
  net: host
  volumes_from:
  - mongo-data
  image: "mongo:2.6.5"
  container_name: mongo
  command: "--smallfiles --keyFile /data/db/mongodb-keyfile --replSet rs0"
